name: SSH Connection

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Connect via SSH
        uses: appleboy/ssh-action@master
        with:
          host: 188.88.198.20
          username: stefan
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Add your SSH commands here
            echo "Connected via SSH"
            # Example: Run a command on the remote server
            ssh user@host "ls -l"